### ISSUE TITLE
could you give me the datasets in convenience?

### ISSUE THREAD

**Issue by WenshuangSong** [mlPOLSL/BACH#17]
Because I need to join with the project as a participant,then I can download the dataset .But the project has been closed! So could you give me the datasets in convenience?
Thanks a lot !

**Comment by myychal** [comment]
Sure, you can use my credentials

http://www.i3s.up.pt/digitalpathology/

*Credentials: *
*Username: team_243*
*Password: Lee0CohLaN*

sob., 28 kwi 2018, 17:28 użytkownik Wenshuang Song <notifications@github.com>
napisał:
